version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    steps:
      - checkout

      # Pre-testing installs
      - run:
          name: Install Dependencies
          command: echo "nothing needs to be installed"

      # Scripts to be run such as tests
      - run:
          name: Before Script
          command: echo "no tests"

      - run:
          name: Display Docker Version
          command: docker --version

      # Build udagram-api-feed image
      - run:
          name: Build udagram-api-feed image
          command: |
            docker build -t udagram-api-feed udagram-api-feed/
            docker tag udagram-api-feed toannguyenofficial/udagram-api-feed:latest

      # Build udagram-api-user image
      - run:
          name: Build udagram-api-user image
          command: |
            docker build -t udagram-api-user udagram-api-user/
            docker tag udagram-api-user toannguyenofficial/udagram-api-user:latest

      # Build reverseproxy image
      - run:
          name: Build reverseproxy image
          command: |
            docker build -t reverseproxy udagram-reverseproxy/
            docker tag reverseproxy toannguyenofficial/reverseproxy:latest

      # Build udagram-frontend image
      - run:
          name: Build udagram-frontend image
          command: |
            docker build -t udagram-frontend udagram-frontend/
            docker tag udagram-frontend toannguyenofficial/udagram-frontend:latest

      # After successful build, push images
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push toannguyenofficial/udagram-api-feed
            docker push toannguyenofficial/udagram-api-user
            docker push toannguyenofficial/reverseproxy
            docker push toannguyenofficial/udagram-frontend
