apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - name: backend-user
        image: brandonodiwuor/udagram-api-user
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret