apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  AWS_BUCKET: bucket-for-udagram-project
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: testing
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres.chvb0iwtndtk.us-east-1.rds.amazonaws.com
  URL: URL=http://localhost:8100